api_platform:
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
            - '%kernel.project_dir%/config/packages/api_platform/resources.yaml'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header