#index:
#    path: /
#    controller: App\Controller\DefaultController::index
supervisor_token:
  path: /supervisor-token
  methods: ['POST']

merchant_pin_token:
  path: /merchant-pin-token
  methods: ['POST']

api_key_nric_token:
  path: /api-key/nric-token
  methods: ['POST']
